server:
  port: 8080
spring:
  application:
    name: logs-sdk
  profiles:
    active: dev
#  zipkin:
#    base-url: http://localhost:9411/
#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus,health,info
#  metrics:
#    tags:
#      application: ${spring.application.name}