server:
  port: 10001
logging:
  config: classpath:logback-kafka.xml
elk:
  kafka:
    url: 127.0.0.1:9092
    topic: logs
spring:
#  zipkin:
#    base-url: http://localhost:9411/
#  cloud:
#    consul:
#      host: 118.195.129.137
#      port: 8500
#      discovery:
#        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
#        prefer-ip-address: true
#健康检查info返回内容，默认空对象{}
#info:
#  app:
#    name: ${spring.application.name}
#    port: ${server.port}
#management:
#  health:
#    cassandra:
#      enabled: true
#spring.cloud.consul.discovery.enabled=false      关闭服务发现
#spring.cloud.consul.discovery.register=false     关闭服务注册
#management.health.consul.enabled=false           关闭健康检查
#${spring.application.name}  服务名称
#${server.port} 服务端口
#instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}